bitget_ws_client::BitgetWsClient
bitget_ws_client.BitgetWsClient::__need_login
bitget_ws_client.BitgetWsClient::__connection
Referenced by bitget_ws_client.BitgetWsClient.__close, bitget_ws_client.BitgetWsClient.__on_open, bitget_ws_client.BitgetWsClient.has_connect.
bitget_ws_client.BitgetWsClient::__login_status
Referenced by bitget_ws_client.BitgetWsClient.__close, bitget_ws_client.BitgetWsClient.__login, bitget_ws_client.BitgetWsClient.__on_message.
bitget_ws_client.BitgetWsClient::__reconnect_status
Referenced by bitget_ws_client.BitgetWsClient.__on_close, bitget_ws_client.BitgetWsClient.__on_error, bitget_ws_client.BitgetWsClient.__on_open, bitget_ws_client.BitgetWsClient.__re_connect.
bitget_ws_client.BitgetWsClient::__api_key
Referenced by bitget_ws_client.BitgetWsClient.__login, bitget_ws_client.BitgetWsClient.api_key.
bitget_ws_client.BitgetWsClient::__api_secret_key
Referenced by bitget_ws_client.BitgetWsClient.__login, bitget_ws_client.BitgetWsClient.api_secret_key.
bitget_ws_client.BitgetWsClient::__passphrase
Referenced by bitget_ws_client.BitgetWsClient.__login, bitget_ws_client.BitgetWsClient.passphrase.
bitget_ws_client.BitgetWsClient::__all_suribe
Referenced by bitget_ws_client.BitgetWsClient.__re_connect, bitget_ws_client.BitgetWsClient.unsubscribe.
bitget_ws_client.BitgetWsClient::__listener
Referenced by bitget_ws_client.BitgetWsClient.__on_message, bitget_ws_client.BitgetWsClient.listener.
bitget_ws_client.BitgetWsClient::__error_listener
Referenced by bitget_ws_client.BitgetWsClient.__on_message, bitget_ws_client.BitgetWsClient.error_listener.
bitget_ws_client.BitgetWsClient::__url
Referenced by bitget_ws_client.BitgetWsClient.__init_client.
bitget_ws_client.BitgetWsClient::__scribe_map
Referenced by bitget_ws_client.BitgetWsClient.subscribe, bitget_ws_client.BitgetWsClient.unsubscribe.
bitget_ws_client.BitgetWsClient::__allbooks_map
Referenced by bitget_ws_client.BitgetWsClient.__check_sum.
bitget_ws_client.BitgetWsClient::__ws_client
def bitget_ws_client.BitgetWsClient.__init__
References sign_utils.check_none.
def bitget_ws_client.BitgetWsClient.build
Referenced by bitget_ws_client.BitgetWsClient.__re_connect.
def bitget_ws_client.BitgetWsClient.api_key
References bitget_ws_client.BitgetWsClient.__api_key.
def bitget_ws_client.BitgetWsClient.api_secret_key
References bitget_ws_client.BitgetWsClient.__api_secret_key.
def bitget_ws_client.BitgetWsClient.passphrase
References bitget_ws_client.BitgetWsClient.__passphrase.
def bitget_ws_client.BitgetWsClient.listener
References bitget_ws_client.BitgetWsClient.__listener.
def bitget_ws_client.BitgetWsClient.error_listener
References bitget_ws_client.BitgetWsClient.__error_listener.
def bitget_ws_client.BitgetWsClient.has_connect
References bitget_ws_client.BitgetWsClient.__connection.
def bitget_ws_client.BitgetWsClient.connect
def bitget_ws_client.BitgetWsClient.send_message
Referenced by bitget_ws_client.BitgetWsClient.__login, bitget_ws_client.BitgetWsClient.subscribe, bitget_ws_client.BitgetWsClient.unsubscribe.
def bitget_ws_client.BitgetWsClient.subscribe
References bitget_ws_client.BitgetWsClient.__scribe_map, bitget_ws_client.BitgetWsClient.send_message.
Referenced by bitget_ws_client.BitgetWsClient.__check_sum, bitget_ws_client.BitgetWsClient.__re_connect.
def bitget_ws_client.BitgetWsClient.unsubscribe
References bitget_ws_client.BitgetWsClient.__all_suribe, bitget_ws_client.BitgetWsClient.__scribe_map, bitget_ws_client.BitgetWsClient.send_message.
Referenced by bitget_ws_client.BitgetWsClient.__check_sum.
def bitget_ws_client.BitgetWsClient.get_listener
References bitget_ws_client.BitgetWsClient.__dict_to_subscribe_req.
Referenced by bitget_ws_client.BitgetWsClient.__on_message.
def bitget_ws_client.BitgetWsClient.__init_client
References bitget_ws_client.BitgetWsClient.__on_close, bitget_ws_client.BitgetWsClient.__on_error, bitget_ws_client.BitgetWsClient.__on_message, bitget_ws_client.BitgetWsClient.__on_open, bitget_ws_client.BitgetWsClient.__url.
def bitget_ws_client.BitgetWsClient.__login
References bitget_ws_client.BitgetWsClient.__api_key, bitget_ws_client.BitgetWsClient.__api_secret_key, bitget_ws_client.BitgetWsClient.__login_status, bitget_ws_client.BitgetWsClient.__passphrase, sign_utils.check_none, sign_utils.pre_hash, bitget_ws_client.BitgetWsClient.send_message, sign_utils.sign.
def bitget_ws_client.BitgetWsClient.__keep_connected
References bitget_ws_client.BitgetWsClient.__keep_connected.
Referenced by bitget_ws_client.BitgetWsClient.__keep_connected.
def bitget_ws_client.BitgetWsClient.__on_open
References bitget_ws_client.BitgetWsClient.__connection, bitget_ws_client.BitgetWsClient.__reconnect_status.
Referenced by bitget_ws_client.BitgetWsClient.__init_client.
def bitget_ws_client.BitgetWsClient.__on_message
References bitget_ws_client.BitgetWsClient.__check_sum, bitget_ws_client.BitgetWsClient.__error_listener, bitget_ws_client.BitgetWsClient.__listener, bitget_ws_client.BitgetWsClient.__login_status, bitget_ws_client.BitgetWsClient.get_listener.
Referenced by bitget_ws_client.BitgetWsClient.__init_client.
def bitget_ws_client.BitgetWsClient.__dict_books_info
Referenced by bitget_ws_client.BitgetWsClient.__check_sum.
def bitget_ws_client.BitgetWsClient.__dict_to_subscribe_req
Referenced by bitget_ws_client.BitgetWsClient.__check_sum, bitget_ws_client.BitgetWsClient.get_listener.
def bitget_ws_client.BitgetWsClient.__on_error
References bitget_ws_client.BitgetWsClient.__close, bitget_ws_client.BitgetWsClient.__re_connect, bitget_ws_client.BitgetWsClient.__reconnect_status.
Referenced by bitget_ws_client.BitgetWsClient.__init_client.
def bitget_ws_client.BitgetWsClient.__on_close
References bitget_ws_client.BitgetWsClient.__close, bitget_ws_client.BitgetWsClient.__re_connect, bitget_ws_client.BitgetWsClient.__reconnect_status.
Referenced by bitget_ws_client.BitgetWsClient.__init_client.
def bitget_ws_client.BitgetWsClient.__re_connect
References bitget_ws_client.BitgetWsClient.__all_suribe, bitget_ws_client.BitgetWsClient.__reconnect_status, bitget_ws_client.BitgetWsClient.build, bitget_ws_client.BitgetWsClient.subscribe.
Referenced by bitget_ws_client.BitgetWsClient.__on_close, bitget_ws_client.BitgetWsClient.__on_error.
def bitget_ws_client.BitgetWsClient.__close
References bitget_ws_client.BitgetWsClient.__connection, bitget_ws_client.BitgetWsClient.__login_status.
Referenced by bitget_ws_client.BitgetWsClient.__on_close, bitget_ws_client.BitgetWsClient.__on_error.
def bitget_ws_client.BitgetWsClient.__check_sum
References bitget_ws_client.BitgetWsClient.__allbooks_map, bitget_ws_client.BitgetWsClient.__dict_books_info, bitget_ws_client.BitgetWsClient.__dict_to_subscribe_req, bitget_ws_client.BitgetWsClient.subscribe, bitget_ws_client.BitgetWsClient.unsubscribe.
Referenced by bitget_ws_client.BitgetWsClient.__on_message.