BitGetTrader::bitget::client::Client
BitGetTrader.bitget.client.Client::API_KEY
Referenced by BitGetTrader.bitget.client.Client._request.
BitGetTrader.bitget.client.Client::API_SECRET_KEY
Referenced by BitGetTrader.bitget.client.Client._request.
BitGetTrader.bitget.client.Client::PASSPHRASE
Referenced by BitGetTrader.bitget.client.Client._request.
BitGetTrader.bitget.client.Client::use_server_time
Referenced by BitGetTrader.bitget.client.Client._request.
BitGetTrader.bitget.client.Client::first
Referenced by BitGetTrader.bitget.client.Client._request.
def BitGetTrader.bitget.client.Client.__init__
def BitGetTrader.bitget.client.Client._request
References BitGetTrader.bitget.client.Client._get_timestamp, BitGetTrader.bitget.client.Client.API_KEY, BitGetTrader.bitget.client.Client.API_SECRET_KEY, BitGetTrader.bitget.client.Client.first, BitGetTrader.bitget.client.Client.PASSPHRASE, BitGetTrader.bitget.client.Client.use_server_time.
Referenced by BitGetTrader.bitget.client.Client._request_with_params, BitGetTrader.bitget.client.Client._request_without_params.
def BitGetTrader.bitget.client.Client._request_without_params
References BitGetTrader.bitget.client.Client._request.
Referenced by BitGetTrader.bitget.spot.account_api.AccountApi.assets, BitGetTrader.bitget.spot.public_api.PublicApi.currencies, BitGetTrader.bitget.spot.public_api.PublicApi.products, BitGetTrader.bitget.mix.trace_api.TraceApi.profit_settle_margin_coin, BitGetTrader.bitget.mix.trace_api.TraceApi.summary, BitGetTrader.bitget.spot.market_api.MarketApi.tickers, BitGetTrader.bitget.spot.public_api.PublicApi.times.
def BitGetTrader.bitget.client.Client._request_with_params
References BitGetTrader.bitget.client.Client._request.
Referenced by BitGetTrader.bitget.mix.account_api.AccountApi.account, BitGetTrader.bitget.mix.account_api.AccountApi.accountBill, BitGetTrader.bitget.mix.account_api.AccountApi.accounts, BitGetTrader.bitget.mix.position_api.PositionApi.all_position, BitGetTrader.bitget.spot.order_api.OrderApi.batch_orders, BitGetTrader.bitget.mix.order_api.OrderApi.batch_orders, BitGetTrader.bitget.spot.account_api.AccountApi.bills, BitGetTrader.bitget.spot.order_api.OrderApi.cancel_batch_orders, BitGetTrader.bitget.mix.order_api.OrderApi.cancel_batch_orders, BitGetTrader.bitget.spot.order_api.OrderApi.cancel_orders, BitGetTrader.bitget.mix.order_api.OrderApi.cancel_orders, BitGetTrader.bitget.mix.plan_api.PlanApi.cancel_plan, BitGetTrader.bitget.spot.market_api.MarketApi.candles, BitGetTrader.bitget.mix.market_api.MarketApi.candles, BitGetTrader.bitget.mix.trace_api.TraceApi.close_track_order, BitGetTrader.bitget.mix.market_api.MarketApi.contracts, BitGetTrader.bitget.mix.order_api.OrderApi.current, BitGetTrader.bitget.mix.market_api.MarketApi.current_fund_rate, BitGetTrader.bitget.mix.plan_api.PlanApi.current_plan, BitGetTrader.bitget.mix.trace_api.TraceApi.current_track, BitGetTrader.bitget.spot.wallet_api.WalletApi.depositAddress, BitGetTrader.bitget.spot.wallet_api.WalletApi.depositList, BitGetTrader.bitget.mix.market_api.MarketApi.depth, BitGetTrader.bitget.spot.market_api.MarketApi.depth, BitGetTrader.bitget.mix.order_api.OrderApi.detail, BitGetTrader.bitget.spot.market_api.MarketApi.fills, BitGetTrader.bitget.mix.market_api.MarketApi.fills, BitGetTrader.bitget.spot.order_api.OrderApi.fills, BitGetTrader.bitget.mix.order_api.OrderApi.fills, BitGetTrader.bitget.mix.trace_api.TraceApi.follower_history_orders, BitGetTrader.bitget.mix.market_api.MarketApi.funding_time, BitGetTrader.bitget.spot.order_api.OrderApi.history, BitGetTrader.bitget.mix.order_api.OrderApi.history, BitGetTrader.bitget.mix.market_api.MarketApi.history_fund_rate, BitGetTrader.bitget.mix.plan_api.PlanApi.history_plan, BitGetTrader.bitget.mix.trace_api.TraceApi.history_track, BitGetTrader.bitget.mix.market_api.MarketApi.index, BitGetTrader.bitget.mix.account_api.AccountApi.leverage, BitGetTrader.bitget.mix.account_api.AccountApi.margin, BitGetTrader.bitget.mix.account_api.AccountApi.margin_mode, BitGetTrader.bitget.mix.market_api.MarketApi.market_price, BitGetTrader.bitget.mix.plan_api.PlanApi.modify_plan, BitGetTrader.bitget.mix.plan_api.PlanApi.modify_plan_preset, BitGetTrader.bitget.mix.plan_api.PlanApi.modify_tpsl_plan, BitGetTrader.bitget.mix.account_api.AccountApi.open_count, BitGetTrader.bitget.mix.market_api.MarketApi.open_interest, BitGetTrader.bitget.spot.order_api.OrderApi.open_order, BitGetTrader.bitget.spot.order_api.OrderApi.order_info, BitGetTrader.bitget.spot.order_api.OrderApi.orders, BitGetTrader.bitget.mix.order_api.OrderApi.place_order, BitGetTrader.bitget.mix.plan_api.PlanApi.place_plan, BitGetTrader.bitget.mix.plan_api.PlanApi.place_tpsl, BitGetTrader.bitget.mix.account_api.AccountApi.position_mode, BitGetTrader.bitget.spot.public_api.PublicApi.product, BitGetTrader.bitget.mix.trace_api.TraceApi.profit_date_detail, BitGetTrader.bitget.mix.trace_api.TraceApi.profit_date_group, BitGetTrader.bitget.mix.position_api.PositionApi.single_position, BitGetTrader.bitget.mix.market_api.MarketApi.ticker, BitGetTrader.bitget.spot.market_api.MarketApi.ticker, BitGetTrader.bitget.mix.market_api.MarketApi.tickers, BitGetTrader.bitget.spot.wallet_api.WalletApi.transfer, BitGetTrader.bitget.mix.trace_api.TraceApi.wait_profit_detail, BitGetTrader.bitget.spot.wallet_api.WalletApi.withdrawal, BitGetTrader.bitget.spot.wallet_api.WalletApi.withdrawalInner, BitGetTrader.bitget.spot.wallet_api.WalletApi.withdrawalList.
def BitGetTrader.bitget.client.Client._get_timestamp
Referenced by BitGetTrader.bitget.client.Client._request.