sign_utils
def sign_utils.sign
Referenced by bitget_ws_client.BitgetWsClient.__login.
def sign_utils.pre_hash
Referenced by bitget_ws_client.BitgetWsClient.__login.
def sign_utils.check_none
Referenced by bitget_ws_client.BitgetWsClient.__init__, bitget_ws_client.BitgetWsClient.__login.